### ISSUE TITLE
Epel has upgraded `easy-rsa` to version 3.x and removed 2.x, breaking the module

### ISSUE THREAD

**Issue by ElvenSpellmaker** [voxpupuli/puppet-openvpn#269] opened 2018-03-07 16:39 UTC
## Affected Puppet, Ruby, OS and module versions/distributions
N/A (At least epel for EL7)

## What are you seeing
`easy-rsa` 3.x has a completely different way of working to version 2.x and so the commands in the module fail to work (`pkitool` for example).
It seems the commands have been rolled into the `easyrsa`  script supplied, but the commands don't seem to quite map 1-2-1 with the original structure of 2.x.

**Comment by monkey670** [comment] 2018-03-09 09:45
Is this not a duplicate of #216?

**Comment by ElvenSpellmaker** [comment] 2018-03-09 09:50
@monkey670  I suppose it seems to be similar, although in this case the module is now broken for all of CentOS 7. I can close this and add a comment in the other issue.

**Comment by NoodlesNZ** [comment] 2018-05-11 05:12
Have added #278 to address this issue

**Closed** 2018-09-11 19:50 UTC
